# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: back test integration

on:
  push:
      branches:
        - '**'
  pull_request:
    branches: [main]
  repository_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: PASS - Dispatch initing repository event
        run: |
          curl -X POST https://api.github.com/repos/OPOII/books-back/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u OPOII:8fb56c907095cc60906abfb75846ee1300bf5458 \
          --data '{"event_type": "PASS", "client_payload": { "repository": "'"https://github.com/OPOII/books-back"'" }}'
      